# -*- coding: utf-8 -*-
"""LLM-Powered Feature.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_njZof1AdsFeVtnochl_16amQ_xw_KF
"""

# Advanced Modeling part 3

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression, Ridge, LogisticRegression
from sklearn.metrics import (
    mean_squared_error, r2_score,
    confusion_matrix, classification_report,
    roc_curve, roc_auc_score,
    precision_score, recall_score, f1_score
)
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.impute import SimpleImputer # Added import
from sklearn.pipeline import Pipeline # Added import
import warnings
warnings.filterwarnings('ignore')

# ------------------------------------------------------------
# 1. Load data and define targets
# ------------------------------------------------------------
df = pd.read_csv('cleaned_data.csv')
print(df.head())
TARGET_REG = 'Price'          # <-- change to your column
y_reg = df[TARGET_REG]
y_clf = (y_reg > y_reg.median()).astype(int)
X = df.drop(columns=[TARGET_REG])
del df   # free original DataFrame

# ------------------------------------------------------------
# 2. Train/test split
# ------------------------------------------------------------
X_train, X_test, y_reg_train, y_reg_test, y_clf_train, y_clf_test = train_test_split(
    X, y_reg, y_clf, test_size=0.2, random_state=42
)
del X, y_reg, y_clf   # free full data

# ------------------------------------------------------------
# 2. Build a preprocessing pipeline (for raw data)
# ------------------------------------------------------------
# Identify categorical and numeric columns
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns.tolist()
num_cols = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Ordinal mappings (if any – modify as needed)
ordinal_mappings = {
    # 'education': ['High School', 'Bachelor', 'Master', 'PhD'],
}

# Build column transformer
transformers = []
for col in cat_cols:
    if col in ordinal_mappings:
        transformers.append(
            (col, OrdinalEncoder(categories=[ordinal_mappings[col]],
                                 handle_unknown='use_encoded_value',
                                 unknown_value=-1), [col])
        )
    else:
        transformers.append(
            (col, OneHotEncoder(drop='first', handle_unknown='ignore',
                                sparse_output=False,   # dense for compatibility
                                min_frequency=0.01, max_categories=20), [col])
        )

preprocessor = ColumnTransformer(transformers, remainder='passthrough')

# Full pipeline: preprocessing + scaling + classifier placeholder
# We'll create a base pipeline without a classifier and then clone it for each model.
base_preprocessor = Pipeline([
    ('preprocessor', preprocessor),
    ('scaler', StandardScaler())   # scaling is fine for tree models too
])

# We'll define a function to get a pipeline with a given classifier
def make_full_pipeline(classifier):
    return Pipeline([
        ('preproc', base_preprocessor),
        ('clf', classifier)
    ])

print("Categorical columns:", cat_cols)
print("Numerical columns:", num_cols)

# ------------------------------------------------------------
# 3. Decision Tree Baseline (unconstrained)
# ------------------------------------------------------------
dt_default = make_full_pipeline(DecisionTreeClassifier(random_state=42))
dt_default.fit(X_train, y_clf_train)
train_acc_def = accuracy_score(y_clf_train, dt_default.predict(X_train))
test_acc_def = accuracy_score(y_clf_test, dt_default.predict(X_test))
print("=== Decision Tree (default) ===")
print(f"Train accuracy: {train_acc_def:.4f}")
print(f"Test accuracy : {test_acc_def:.4f}\n")

# ------------------------------------------------------------
# 4. Controlled Decision Tree (max_depth=5, min_samples_split=20)
# ------------------------------------------------------------
dt_controlled = make_full_pipeline(DecisionTreeClassifier(
    max_depth=5, min_samples_split=20, random_state=42
))
dt_controlled.fit(X_train, y_clf_train)
train_acc_ctrl = accuracy_score(y_clf_train, dt_controlled.predict(X_train))
test_acc_ctrl = accuracy_score(y_clf_test, dt_controlled.predict(X_test))
print("=== Decision Tree (controlled) ===")
print(f"Train accuracy: {train_acc_ctrl:.4f}")
print(f"Test accuracy : {test_acc_ctrl:.4f}\n")

#------------------------------------------------------------
# 5. Gini vs Entropy (controlled, max_depth=5)
# ------------------------------------------------------------
dt_gini = make_full_pipeline(DecisionTreeClassifier(
    criterion='gini', max_depth=5, random_state=42
))
dt_gini.fit(X_train, y_clf_train)
test_acc_gini = accuracy_score(y_clf_test, dt_gini.predict(X_test))

dt_entropy = make_full_pipeline(DecisionTreeClassifier(
    criterion='entropy', max_depth=5, random_state=42
))
dt_entropy.fit(X_train, y_clf_train)
test_acc_entropy = accuracy_score(y_clf_test, dt_entropy.predict(X_test))

print("=== Gini vs Entropy (test accuracy) ===")
print(f"Gini    : {test_acc_gini:.4f}")
print(f"Entropy : {test_acc_entropy:.4f}\n")

# ------------------------------------------------------------
# 6. Random Forest (n_estimators=100, max_depth=10)
# ------------------------------------------------------------
rf = make_full_pipeline(RandomForestClassifier(
    n_estimators=100, max_depth=10, random_state=42
))
rf.fit(X_train, y_clf_train)
rf_train_acc = accuracy_score(y_clf_train, rf.predict(X_train))
rf_test_acc = accuracy_score(y_clf_test, rf.predict(X_test))
rf_auc = roc_auc_score(y_clf_test, rf.predict_proba(X_test)[:, 1])
print("=== Random Forest ===")
print(f"Train accuracy: {rf_train_acc:.4f}")
print(f"Test accuracy : {rf_test_acc:.4f}")
print(f"Test AUC      : {rf_auc:.4f}")

# Feature importances
# Need to extract the trained RandomForest from the pipeline
rf_model = rf.named_steps['clf']
# Get feature names after preprocessing
preproc = rf.named_steps['preproc']
# Transform training data to get feature names
X_train_trans = preproc.transform(X_train)
preprocessor_obj = preproc.named_steps['preprocessor']
# Get feature names after preprocessing
try:
    feature_names = preprocessor_obj.get_feature_names_out()
except AttributeError:
    # fallback: use generic names
    feature_names = [f"feat_{i}" for i in range(X_train_trans.shape[1])]

importances = rf_model.feature_importances_
sorted_idx = np.argsort(importances)[::-1]
print("\nTop 5 feature importances:")
for i in range(5):
    print(f"{feature_names[sorted_idx[i]]}: {importances[sorted_idx[i]]:.4f}")

import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier # Ensure these are imported
from sklearn.tree import DecisionTreeClassifier # Ensure this is imported
from sklearn.metrics import accuracy_score, roc_auc_score # Ensure these are imported
from sklearn.pipeline import Pipeline # Ensure this is imported
from sklearn.impute import SimpleImputer # Ensure this is imported
from sklearn.preprocessing import StandardScaler, OneHotEncoder # Ensure these are imported
from sklearn.compose import ColumnTransformer # Ensure this is imported


# ------------------------------------------------------------
# 7. Gradient Boosting (n_estimators=100, learning_rate=0.1, max_depth=3)
# ------------------------------------------------------------

# --- Start of modifications for NaN handling ---
# Re-define preprocessing pipeline elements locally to include SimpleImputer for numerical columns.
# This addresses the ValueError: Input X contains NaN for GradientBoostingClassifier.
# This duplicates code from previous cells but adheres to the instruction to only modify this cell.

# Re-declaring key variables from earlier cells to ensure local scope for this fix
cat_cols = ['Invoice', 'StockCode', 'Description', 'InvoiceDate', 'Country']
num_cols = ['Quantity', 'Customer ID']
# ordinal_mappings = {} # Based on previous cell, it was empty, no need to redefine if not used

# Define preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')), # Impute NaNs in categorical columns
    ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore',
                             sparse_output=False,
                             min_frequency=0.01, max_categories=20))
])

# Create the ColumnTransformer
preprocessor_fixed = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, num_cols),
        ('cat', categorical_transformer, cat_cols)
    ],
    remainder='passthrough' # Any columns not specified will be passed through (e.g., if any new ones appear)
)

# Re-create the base_preprocessor. Note: StandardScaler is now part of numerical_transformer,
# so it's not needed at the top level of base_preprocessor anymore.
base_preprocessor_fixed = Pipeline([
    ('preprocessor', preprocessor_fixed)
])

# Re-create the make_full_pipeline function to use the fixed base_preprocessor
def make_full_pipeline_fixed(classifier):
    return Pipeline([
        ('preproc', base_preprocessor_fixed),
        ('clf', classifier)
    ])
# --- End of modifications for NaN handling ---


gb = make_full_pipeline_fixed(GradientBoostingClassifier( # Use the new fixed pipeline function
    n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42
))
gb.fit(X_train, y_clf_train)
gb_train_acc = accuracy_score(y_clf_train, gb.predict(X_train))
gb_test_acc = accuracy_score(y_clf_test, gb.predict(X_test))
gb_auc = roc_auc_score(y_clf_test, gb.predict_proba(X_test)[:, 1])
print("\n=== Gradient Boosting ===")
print(f"Train accuracy: {gb_train_acc:.4f}")
print(f"Test accuracy : {gb_test_acc:.4f}")
print(f"Test AUC      : {gb_auc:.4f}")

# ------------------------------------------------------------
# 8. Feature ablation (remove 5 lowest‑importance features)
# ------------------------------------------------------------

# Re-create the Random Forest pipeline and calculate its AUC
# This ensures 'rf' and 'rf_auc' are defined even if previous cells are not run in order
rf = make_full_pipeline(RandomForestClassifier(
    n_estimators=100, max_depth=10, random_state=42
))
rf.fit(X_train, y_clf_train)
rf_auc = roc_auc_score(y_clf_test, rf.predict_proba(X_test)[:, 1])

# Re-extract feature importances and names from the RF model
rf_model = rf.named_steps['clf']
preproc = rf.named_steps['preproc']

X_train_trans = preproc.transform(X_train)
preprocessor_obj = preproc.named_steps['preprocessor']

try:
    feature_names = preprocessor_obj.get_feature_names_out()
except AttributeError:
    feature_names = [f"feat_{i}" for i in range(X_train_trans.shape[1])]

importances = rf_model.feature_importances_

# Get importance and sort ascending
lowest_idx = np.argsort(importances)[:5]   # indices of lowest 5
lowest_feature_names = [feature_names[i] for i in lowest_idx]
print(f"\nRemoving features: {lowest_feature_names}")

# We need to remove these from the preprocessed data (scaled)
# We'll refit the preprocessor on training to get transformed data
X_train_trans = preproc.transform(X_train)
X_test_trans = preproc.transform(X_test)
# Create reduced versions without those columns
X_train_reduced = np.delete(X_train_trans, lowest_idx, axis=1)
X_test_reduced = np.delete(X_test_trans, lowest_idx, axis=1)

# Train a new Random Forest on reduced data (no pipeline for simplicity)
rf_reduced = RandomForestClassifier(
    n_estimators=100, max_depth=10, random_state=42
)
rf_reduced.fit(X_train_reduced, y_clf_train)
rf_reduced_auc = roc_auc_score(y_clf_test, rf_reduced.predict_proba(X_test_reduced)[:, 1])

print(f"AUC full model    : {rf_auc:.4f}")
print(f"AUC reduced model : {rf_reduced_auc:.4f}")

from sklearn.model_selection import StratifiedKFold, cross_val_score # Added imports

# ------------------------------------------------------------
# 9. Cross‑validated comparison (5‑fold StratifiedKFold)
# ------------------------------------------------------------
# Models to compare: Logistic Regression (from Part 2), controlled DT, RF, GBoost
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

models = {
    'Logistic Regression': make_full_pipeline_fixed(LogisticRegression(max_iter=1000, random_state=42)),
    'Decision Tree (controlled)': make_full_pipeline_fixed(DecisionTreeClassifier(max_depth=5, min_samples_split=20, random_state=42)),
    'Random Forest': make_full_pipeline_fixed(RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)),
    'Gradient Boosting': make_full_pipeline_fixed(GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42))
}

print("\n=== Cross‑validated AUC (mean \u00b1 std) ===")
cv_results = {}
for name, model in models.items():
    scores = cross_val_score(model, X_train, y_clf_train, cv=cv, scoring='roc_auc')
    cv_results[name] = scores
    print(f"{name:25s}: {scores.mean():.4f} \u00b1 {scores.std():.4f}")

from sklearn.model_selection import GridSearchCV, StratifiedKFold # Added StratifiedKFold import

# ------------------------------------------------------------
# 10. GridSearchCV on Random Forest (with full Pipeline on raw data)
# ------------------------------------------------------------

# Re-declaring key variables and pipeline components for robustness within this cell
# This ensures proper NaN handling during GridSearchCV
cat_cols = ['Invoice', 'StockCode', 'Description', 'InvoiceDate', 'Country']
num_cols = ['Quantity', 'Customer ID']

# Define preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore',
                             sparse_output=False,
                             min_frequency=0.01, max_categories=20))
])

# Create the ColumnTransformer
preprocessor_grid_search = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, num_cols),
        ('cat', categorical_transformer, cat_cols)
    ],
    remainder='passthrough'
).set_output(transform="pandas") # Explicitly set output to pandas DataFrame

# Re-create the base_preprocessor to include imputation
base_preprocessor_grid_search = Pipeline([
    ('preprocessor', preprocessor_grid_search)
])

# We'll build a pipeline with the preprocessor + RF
pipe_rf = Pipeline([
    ('preproc', base_preprocessor_grid_search),
    ('rf', RandomForestClassifier(random_state=42))
])

param_grid = {
    'rf__n_estimators': [50, 100, 200],
    'rf__max_depth': [5, 10, None],
    'rf__min_samples_leaf': [1, 5]
}

grid_search = GridSearchCV(
    pipe_rf, param_grid, cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
    scoring='roc_auc', n_jobs=-1, verbose=1
)
grid_search.fit(X_train, y_clf_train)

print("\n=== GridSearchCV Results ===")
print(f"Best params: {grid_search.best_params_}")
print(f"Best CV AUC: {grid_search.best_score_:.4f}")

best_pipeline = grid_search.best_estimator_

# ------------------------------------------------------------
# 11. Manual learning curve (best pipeline on 20%‑100% of training)
# ------------------------------------------------------------

best_pipeline = None # Initialize to ensure it's always defined
fallback_used = False

if 'grid_search' in globals():
    try:
        # Attempt to get best_estimator_ from grid_search
        best_pipeline = grid_search.best_estimator_
        if best_pipeline is None: # Additional check if best_estimator_ was somehow set to None
            raise AttributeError("grid_search.best_estimator_ is None")
    except AttributeError:
        # If grid_search exists but best_estimator_ is not available (e.g., due to KeyboardInterrupt)
        print("Warning: 'grid_search.best_estimator_' not found. Initializing 'best_pipeline' with a default Random Forest.")
        print("Please ensure Cell 10 (GridSearchCV) completes for the actual best pipeline.")
        fallback_used = True
else:
    # If grid_search object itself is not in globals()
    print("Warning: 'grid_search' not found. Initializing 'best_pipeline' with a default Random Forest.")
    print("Please ensure Cell 10 (GridSearchCV) completes for the actual best pipeline.")
    fallback_used = True

# If fallback is needed, define best_pipeline with a default model
if fallback_used:
    # Re-create make_full_pipeline_fixed and its dependencies if not available
    # This block ensures 'make_full_pipeline_fixed' and its dependencies are present
    # even if previous cells were skipped or modified.
    if 'make_full_pipeline_fixed' not in globals():
        cat_cols = ['Invoice', 'StockCode', 'Description', 'InvoiceDate', 'Country']
        num_cols = ['Quantity', 'Customer ID']

        numerical_transformer = Pipeline([
            ('imputer', SimpleImputer(strategy='mean')),
            ('scaler', StandardScaler())
        ])

        categorical_transformer = Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore',
                                     sparse_output=False,
                                     min_frequency=0.01, max_categories=20))
        ])

        preprocessor_fixed = ColumnTransformer(
            transformers=[
                ('num', numerical_transformer, num_cols),
                ('cat', categorical_transformer, cat_cols)
            ],
            remainder='passthrough'
        )

        base_preprocessor_fixed = Pipeline([
            ('preprocessor', preprocessor_fixed)
        ])

        def make_full_pipeline_fixed(classifier):
            return Pipeline([
                ('preproc', base_preprocessor_fixed),
                ('clf', classifier)
            ])

    best_pipeline = make_full_pipeline_fixed(
        RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
    )

fractions = [0.2, 0.4, 0.6, 0.8, 1.0]
train_aucs = []
test_aucs = []

for f in fractions:
    size = int(f * len(X_train))
    X_train_sub = X_train.iloc[:size]
    y_train_sub = y_clf_train.iloc[:size]
    # Clone the best pipeline and fit on subset
    pipe_clone = Pipeline(best_pipeline.steps)
    pipe_clone.fit(X_train_sub, y_train_sub)
    # Training AUC on the same subset
    train_pred_proba = pipe_clone.predict_proba(X_train_sub)[:, 1]
    train_auc = roc_auc_score(y_train_sub, train_pred_proba)
    # Test AUC on full test set
    test_pred_proba = pipe_clone.predict_proba(X_test)[:, 1]
    test_auc = roc_auc_score(y_clf_test, test_pred_proba)
    train_aucs.append(train_auc)
    test_aucs.append(test_auc)

print("\n=== Learning Curve ===")
print("Fraction | Train AUC | Test AUC")
for f, ta, tea in zip(fractions, train_aucs, test_aucs):
    print(f"{f:8.1f} | {ta:.4f}    | {tea:.4f}")

# 12. Serialize best model
joblib.dump(best_pipeline, 'best_model.pkl')
print("\nModel saved as 'best_model.pkl'")

# 13. Reload and predict on two rows
loaded_model = joblib.load('best_model.pkl')
sample_rows = X.iloc[:2]   # raw rows
preds = loaded_model.predict(sample_rows)
probas = loaded_model.predict_proba(sample_rows)[:, 1]
print("Predictions on first two rows:")
print(f"Classes: {preds}")
print(f"Probabilities: {probas}")

import joblib

joblib.dump(best_pipeline, "best_model.pkl")

#  LLM-Powered Feature part 4

import os
import json
import re
import requests
import joblib
import pandas as pd
import numpy as np
from jsonschema import validate, ValidationError
from sklearn.model_selection import train_test_split

# ------------------------------------------------------------
# 1. Load model and data
# ------------------------------------------------------------
# Load the best model from Part 3
model = joblib.load('best_model.pkl')

# Load original data to get column names and preprocessing
df = pd.read_csv('cleaned_data.csv')
TARGET_REG = 'Price'  # adjust to your column name

# Create features and target
y_reg = df[TARGET_REG]
y_clf = (y_reg > y_reg.median()).astype(int)
X = df.drop(columns=[TARGET_REG])

# Get feature names for constructing inputs
feature_names = X.columns.tolist()

# Split the data to get training columns (same as Part 3)
X_train, X_test, y_clf_train, y_clf_test = train_test_split(
    X, y_clf, test_size=0.2, random_state=42
)

print(f"Model loaded successfully!")
print(f"Expected features: {len(feature_names)} columns")
print(f"First 5 features: {feature_names[:5]}")
print(f"Model type: {type(model)}")
print(f"Model steps: {model.named_steps.keys()}")

import os

os.environ["LLM_API_KEY"] = "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"

API_KEY = os.environ.get("LLM_API_KEY")

import os
print(f"LLM_API_KEY from os.environ: {os.environ.get('LLM_API_KEY')}")

# ------------------------------------------------------------
# 2. LLM API setup
# ------------------------------------------------------------
API_KEY = os.environ.get('LLM_API_KEY')
if not API_KEY:
    print("WARNING: LLM_API_KEY environment variable not set!")
    print("Please set it with: export LLM_API_KEY='your-api-key-here'")
    # For testing purposes, you can set a dummy key (but don't commit this!)
    # API_KEY = "dummy-key-for-testing"

API_URL = "https://openrouter.ai/api/v1/chat/completions"  # or your endpoint
MODEL_NAME = "gpt-3.5-turbo"  # adjust as needed

def call_llm(system_prompt, user_prompt, temperature=0.0, max_tokens=512):
    """Reusable function to call LLM API"""
    if not API_KEY:
        print("No API key available - returning mock response")
        # Return a mock response for testing without API
        return json.dumps({
            "prediction_label": "High price" if "5000" in user_prompt else "Low price",
            "confidence_level": "high" if "5000" in user_prompt else "medium",
            "top_reason": "Based on feature analysis",
            "second_reason": "Additional factor considered",
            "next_step": "Review recommendation"
        })

    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": MODEL_NAME,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": temperature,
        "max_tokens": max_tokens
    }

    try:
        response = requests.post(API_URL, headers=headers, json=payload, timeout=30)
        if response.status_code == 200:
            return response.json()['choices'][0]['message']['content']
        else:
            print(f"API Error: Status {response.status_code}")
            print(f"Response: {response.text}")
            return None
    except Exception as e:
        print(f"Request failed: {e}")
        return None

# Test the API connection
print("\nTesting API connection...")
test_response = call_llm(
    system_prompt="You are a helpful assistant.",
    user_prompt="Reply with only the word: deva",
    temperature=0.0
)
print(f"Test response: {test_response}\n")

# ------------------------------------------------------------
# 3. Define schema for validation
# ------------------------------------------------------------
EXPLANATION_SCHEMA = {
    "type": "object",
    "properties": {
        "prediction_label": {"type": "string"},
        "confidence_level": {"type": "string", "enum": ["low", "medium", "high"]},
        "top_reason": {"type": "string"},
        "second_reason": {"type": "string"},
        "next_step": {"type": "string"}
    },
    "required": ["prediction_label", "confidence_level", "top_reason", "second_reason", "next_step"]
}

# ------------------------------------------------------------
# 4. PII guardrail
# ------------------------------------------------------------
def has_pii(text):
    """Check for PII in text"""
    email_pattern = r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+'
    phone_pattern = r'\b\d{10}\b|\b\d{3}[-.\s]\d{3}[-.\s]\d{4}\b'
    return bool(re.search(email_pattern, str(text)) or re.search(phone_pattern, str(text)))

# Test guardrail
print("Testing PII guardrail...")
test_inputs = [
    "This is clean text with no PII",
    "Contact me at john.doe@email.com for details",
    "Call me at 555-123-4567"
]
for test in test_inputs:
    print(f"Input: {test}")
    print(f"Blocked: {has_pii(test)}\n")

# ------------------------------------------------------------
# 5. System prompt and user prompt template
# ------------------------------------------------------------
SYSTEM_PROMPT = """You are a model prediction explainer. Your role is to explain why a machine learning model made a specific prediction.

Given feature values, a predicted class (0 or 1), and a probability score, provide a structured JSON explanation.

Follow these rules:
1. Output ONLY valid JSON with these fields:
   - prediction_label: "High price" if class=1, "Low price" if class=0
   - confidence_level: "high" if probability > 0.8, "medium" if 0.5-0.8, "low" if < 0.5
   - top_reason: The single most important factor driving this prediction
   - second_reason: The second most important factor
   - next_step: Recommended action based on the prediction

2. Base your explanation on the feature values provided.
3. Use domain knowledge about housing prices (sqft, waterfront, condition, etc.)
4. Be specific and data-driven in your reasoning.
5. Do not include any text outside the JSON object."""

def construct_user_prompt(features, pred_class, pred_proba):
    """Construct user prompt from features and predictions"""
    feature_str = "\n".join([f"  {k}: {v}" for k, v in features.items()])
    return f"""Please explain the following prediction:

Feature values:
{feature_str}

Predicted class: {pred_class} ({"High price" if pred_class == 1 else "Low price"})
Prediction probability: {pred_proba:.3f}

Provide a JSON explanation with the required fields."""

# ------------------------------------------------------------
# 6. Helper function to validate LLM output
# ------------------------------------------------------------
def validate_explanation(response_text, fallback=None):
    """Validate LLM response against schema"""
    if fallback is None:
        fallback = {
            "prediction_label": "unknown",
            "confidence_level": "low",
            "top_reason": "unable to generate explanation",
            "second_reason": "unable to generate explanation",
            "next_step": "human review required"
        }

    try:
        # Clean the response - remove markdown code blocks if present
        cleaned = response_text.strip()
        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]
        if cleaned.startswith("```"):
            cleaned = cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]

        parsed = json.loads(cleaned.strip())
        validate(instance=parsed, schema=EXPLANATION_SCHEMA)
        return parsed
    except json.JSONDecodeError as e:
        print(f"JSON decode error: {e}")
        print(f"Raw response: {response_text[:200]}...")
        return fallback
    except ValidationError as e:
        print(f"Schema validation error: {e}")
        return fallback

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 7. Function to encode record for prediction
# ------------------------------------------------------------
def encode_record(features):
    """
    Encode a single record using the model's preprocessor.
    This function prepares a single record (features dictionary) into a pandas DataFrame
    that matches the structure and dtypes of the X_train DataFrame, which the full
    model pipeline expects as input.
    """

    # 1. Create a DataFrame from the input features
    df_input = pd.DataFrame([features])

    # 2. Reindex df_input to ensure all columns from X_train are present and in the correct order.
    #    Missing columns will be filled with NaN. Any extra columns in 'features' will be dropped.
    df_input = df_input.reindex(columns=X_train.columns)

    # 3. Ensure consistent dtypes for ColumnTransformer.
    #    Numerical columns are converted to float to handle potential NaNs.
    #    Object/string columns are ensured to be of string type.
    for col in X_train.columns:
        original_dtype = X_train[col].dtype
        if pd.api.types.is_numeric_dtype(original_dtype):
            # Convert to float to allow for NaN. Use errors='coerce' for robustness.
            df_input[col] = pd.to_numeric(df_input[col], errors='coerce')
        elif pd.api.types.is_object_dtype(original_dtype):
            # Ensure object columns (like strings, dates as strings) are of string type
            df_input[col] = df_input[col].astype(str)

    # DEBUG prints to verify df_input structure before returning
    print(f"--- DEBUG (encode_record) START ---")
    print(f"DEBUG (encode_record): df_input type: {type(df_input)}")
    print(f"DEBUG (encode_record): df_input columns: {df_input.columns.tolist()}")
    print(f"DEBUG (encode_record): df_input dtypes:\n{df_input.dtypes}")
    print(f"DEBUG (encode_record): df_input head:\n{df_input.head()}")
    print(f"DEBUG (encode_record): df_input NaNs:\n{df_input.isnull().sum()}")
    print(f"DEBUG (encode_record): df_input.info():")
    df_input.info() # This prints directly to stdout
    print(f"--- DEBUG (encode_record) END ---")

    # Return the prepared DataFrame. The actual transformation will be done by the model pipeline.
    return df_input

# ------------------------------------------------------------
# 8. Main pipeline for Track C
# ------------------------------------------------------------
def explain_prediction(features):
    """Full pipeline: predict + explain using LLM"""
    # Step 1: Check for PII
    feature_str = str(features)
    if has_pii(feature_str):
        print("Input blocked: PII detected.")
        return None, None, None, None

    # Step 2: Encode and predict
    try:
        # encode_record now returns a DataFrame, which the full model pipeline expects.
        df_for_prediction = encode_record(features)
        pred_class = model.predict(df_for_prediction)[0]
        pred_proba = model.predict_proba(df_for_prediction)[0][1]  # probability of class 1
    except Exception as e:
        print(f"Prediction failed: {e}")
        import traceback
        traceback.print_exc() # Print full traceback
        return None, None, None, None

    # Step 3: Construct user prompt
    user_prompt = construct_user_prompt(features, pred_class, pred_proba)

    # Step 4: Call LLM
    llm_response = call_llm(SYSTEM_PROMPT, user_prompt, temperature=0.0)

    if llm_response is None:
        print("LLM call failed")
        return pred_class, pred_proba, None, None

    # Step 5: Validate output
    explanation = validate_explanation(llm_response)

    return pred_class, pred_proba, llm_response, explanation

#------------------------------------------------------------
# 9. Demonstration with three hand-crafted inputs
# ------------------------------------------------------------
print("\n" + "="*60)
print("Track C: Model Prediction Explanation Pipeline")
print("="*60 + "\n")

# Create three hand-crafted feature vectors
# Based on actual features from your dataset (feature_names)

inputs = []

# Input 1: Example for a potentially 'High price' prediction
# (Assuming higher quantity/specific product contributes to higher price classification)
input1 = {
    'Invoice': '536365', # Example invoice number
    'StockCode': '85123A', # Example stock code
    'Description': 'WHITE HANGING HEART T-LIGHT HOLDER', # Example description
    'Quantity': 100, # High quantity
    'InvoiceDate': '2010-12-01 08:26:00', # Example date
    'Customer ID': 17850.0, # Example customer ID
    'Country': 'United Kingdom' # Example country
}
inputs.append(input1)

# Input 2: Example for a potentially 'Low price' prediction
# (Assuming lower quantity/less valuable product contributes to lower price classification)
input2 = {
    'Invoice': '536366',
    'StockCode': '22629',
    'Description': 'SPACEBOY LUNCH BOX ',
    'Quantity': 1, # Low quantity
    'InvoiceDate': '2010-12-01 08:28:00',
    'Customer ID': 17850.0,
    'Country': 'United Kingdom'
}
inputs.append(input2)

# Input 3: Example for an 'Average price' prediction
# (Assuming moderate quantity/common product)
input3 = {
    'Invoice': '536367',
    'StockCode': '22728',
    'Description': 'ALARM CLOCK BAKELIKE PINK',
    'Quantity': 10, # Moderate quantity
    'InvoiceDate': '2010-12-01 08:34:00',
    'Customer ID': 17850.0,
    'Country': 'France' # Different country
}
inputs.append(input3)

# Run pipeline on all inputs
results = []
for i, features in enumerate(inputs, 1):
    print(f"\n--- Input {i} ---")
    print(f"Features: {features}") # Print all features to verify

    pred_class, pred_proba, llm_response, explanation = explain_prediction(features)

    if pred_class is not None:
        print(f"Predicted class: {pred_class}")
        print(f"Probability: {pred_proba:.3f}")
    else:
        print("Prediction failed")
        continue

    if llm_response:
        print(f"LLM Response: {llm_response[:200]}...")
    else:
        print("No LLM response")

    if explanation:
        print(f"Validated Explanation: {explanation}")
    else:
        print("Validation failed")

    results.append({
        'input': features,
        'pred_class': pred_class,
        'pred_proba': pred_proba,
        'llm_response': llm_response,
        'explanation': explanation,
        'valid': explanation is not None and explanation != {
            "prediction_label": "unknown",
            "confidence_level": "low",
            "top_reason": "unable to generate explanation",
            "second_reason": "unable to generate explanation",
            "next_step": "human review required"
        }
    })

# ------------------------------------------------------------
# 10. Temperature comparison (0 vs 0.7)
# ------------------------------------------------------------
print("\n" + "="*60)
print("Temperature Comparison (0 vs 0.7)")
print("="*60 + "\n")

# Use first input for comparison
if inputs:
    test_input = inputs[0]

    for temp in [0.0, 0.7]:
        print(f"\n--- Temperature {temp} ---")
        # Use a mock prediction for consistent comparison
        user_prompt = construct_user_prompt(
            test_input,
            1,  # class 1 (high price)
            0.85  # probability
        )
        response = call_llm(SYSTEM_PROMPT, user_prompt, temperature=temp)
        if response:
            print(f"Response: {response[:200]}...")

            # Validate
            explanation = validate_explanation(response)
            print(f"Validated: {explanation is not None}")
        else:
            print("No response received")

# ------------------------------------------------------------
# 11. Guardrail demonstration
# ------------------------------------------------------------
print("\n" + "="*60)
print("PII Guardrail Test")
print("="*60 + "\n")

pii_test_inputs = [
    {
        'sqft_living': 20000,
        'waterfront': 0,
        'condition': 3,
        'grade': 7,
        'yr_built': 1995,
        'email': 'test@example.com'  # contains PII
    },
    {
        'sqft_living': 2000,
        'waterfront': 0,
        'condition': 3,
        'grade': 7,
        'yr_built': 1995
    }
]

for idx, test_input in enumerate(pii_test_inputs, 1):
    print(f"\nTest {idx}:")
    feature_str = str(test_input)
    blocked = has_pii(feature_str)
    print(f"Features: {feature_str[:100]}...")
    print(f"Blocked: {blocked}")

    if not blocked:
        print("Proceeding to LLM call...")
        pred_class, pred_proba, response, explanation = explain_prediction(test_input)
        print(f"Response received: {response is not None}")
    else:
        print("Skipped - PII detected")

print("\n" + "="*60)
print("Pipeline Complete!")
print("="*60)

# ------------------------------------------------------------
# 12. Summary table
# ------------------------------------------------------------
print("\n" + "="*60)
print("Summary Results Table")
print("="*60)
print("\nInput | Pred Class | Probability | Valid JSON | Guardrail")
print("-"*60)
for i, result in enumerate(results, 1):
    status = "✅ Pass" if result['valid'] else "❌ Fail"
    guardrail = "✅ Pass" if not has_pii(str(result['input'])) else "❌ Blocked"
    print(f"{i}     | {result['pred_class']}          | {result['pred_proba']:.3f}      | {status}    | {guardrail}")